Added Directory on Paper One_shot_Face_Reenactment
DagsHub/papers-with-everything pull request #23
Opened 2022-10-09 17:36 UTC by Bharat-mtr

This is regarding Issue  #21 
Added directory for Paper One_shot_Face_Reenactment.

Paper :- https://arxiv.org/pdf/1908.03251

Repository:- https://dagshub.com/Bharat-mtr/One_Shot_Face_Reenactment

2022-10-09 17:36 UTC, Bharat-mtr commented
@nirbarazida  Please review and let me know if I need to add/edit anything.

2022-10-09 21:01 UTC, Bharat-mtr commented
Fixes #21

2022-10-18 06:16 UTC, deanp70 requested changes
Overall this is another great contribution! Thanks for taking part!

I have one comment to fix – there are a lot of redundant mac related files and folders, mainly a `_MACOSX` folder here: https://dagshub.com/Bharat-mtr/One_Shot_Face_Reenactment/src/master/sample_images/LOFR%20synthetic%20images as well as `.DS_Store` files all over the project. Could you please remove them, as they aren't necessary, take up space, and make navigation more confusing.

After they are removed, we can merge this in.

Thanks again,
Dean

2022-10-18 06:19 UTC, deanp70 commented on One-shot Face Reenactment/README.md
> +<img src="https://github.com/bj80heyue/Learning_One_Shot_Face_Reenactment/blob/master/pics/main.png" width = 900 align=middle>
```suggestion
<img src="https://dagshub.com/Bharat-mtr/One_Shot_Face_Reenactment/raw/master/pics/main.png" width = 900 align=middle>
```

2022-10-18 06:43 UTC, Bharat-mtr commented
> Overall this is another great contribution! Thanks for taking part!
> 
> I have one comment to fix – there are a lot of redundant mac related files and folders, mainly a `_MACOSX` folder here: https://dagshub.com/Bharat-mtr/One_Shot_Face_Reenactment/src/master/sample_images/LOFR%20synthetic%20images as well as `.DS_Store` files all over the project. Could you please remove them, as they aren't necessary, take up space, and make navigation more confusing.
> 
> After they are removed, we can merge this in.
> 
> Thanks again, Dean

I have removed the redundancy. Although the DagsHub repo is taking time to get in sync with Github repo changes.

2022-10-18 07:14 UTC, deanp70 commented
Have you pushed the new git version? It shows me last update was a week ago.

Let me know once it's pushed and I'll re-check

2022-10-18 09:45 UTC, Bharat-mtr commented
> Have you pushed the new git version? It shows me last update was a week ago.
> 
> Let me know once it's pushed and I'll re-check

I have pushed changes to corresponding git repo of One_Shot DagsHub Repo 
Git repo :- https://github.com/Bharat-mtr/One_Shot_Face_Reenactment

Its taking time to show same changes in DagsHub Repo

https://dagshub.com/Bharat-mtr/One_Shot_Face_Reenactment

its showing sync in progress, although I have committed the changes in git repo.

2022-10-18 12:52 UTC, deanp70 approved these changes
Looks good to me, the sync has been complete. Will merge this in.

Thanks again for your contribution!

2022-10-18 12:52 UTC, merged